apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailfrom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/0kaba0/k8s_mailfrom.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - ../helm_values/values-micro-seconddns.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
