apiVersion: v1
kind: Service
metadata:
  name: mailfrom
  labels:
    app: mailfrom
spec:
  type: ClusterIP
  selector:
    app: mailfrom
  ports:
    - name: milter
      port: {{ .Values.milterPort }}
      targetPort: milter
      protocol: TCP
